shadow-exclude = ["x = 0 && y = 0 && override_redirect = true"];

active-opacity = 1;
inactive-opacity = 0.9;
frame-opacity = 1;
inactive-opacity-override = 1;
inactive-dim = 0.2;

opacity-rule = [
  "100:class_g = 'dmenu' && focused",
];

focus-exclude = ["x = 0 && y = 0 && override_redirect = true"];

