#!/usr/bin/env bash

PID=""

if [[ -n $1 ]]; then
    PID=$1
else
    if read -r -t1 input; then
        PID=${input}
    else
        echo "No PID provided."; exit 1
    fi
fi

gdb --batch -ex "thread apply all bt" -p "$PID"
