#!/usr/bin/env bash

# shellcheck disable=SC1090

[ -d $HOME/.scripts ] && PATH="$PATH:$HOME/.scripts"
[ -d $HOME/.local/bin ] && PATH="$PATH:$HOME/.local/bin"

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
