#!/usr/bin/env bash
# shellcheck disable=SC1090,SC2155
# source environment specific configuration first
[ -f "$HOME/.config/bash/.bashrc_host_specific" ] && . "$HOME/.config/bash/.bashrc_host_specific"

# enter the context
[ -f "$HOME/.config/bash/.context" ] && source "$HOME/.config/bash/.context"

if [[ ! "$PATH" == ${HOME}/.local/bin* ]]; then
  export PATH="${PATH:+${PATH}:}${HOME}/.local/bin"
fi

if [[ ! "$PATH" == *${HOME}/.scripts* ]]; then
  export PATH="${PATH:+${PATH}:}${HOME}/.scripts"
fi

shopt -s direxpand

[ -f /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

[ -d "$HOME/.config/bash/bash_completion.d" ] && for f in "$HOME/.config/bash/bash_completion.d/"*; do
    source "${f}"
done

# custom functions
[ -f "$HOME/.config/bash/functions.sh" ] && source "$HOME/.config/bash/functions.sh"

export XDG_CONFIG_HOME=$HOME/.config
export XDG_RUNTIME_DIR=/run/user/$(id -u)
# unlimited history
HISTSIZE=
HISTFILESIZE=
# avoid duplication in bash history
export HISTCONTROL='ignoreboth:erasedups'
shopt -s histappend
# ensure utf8
export LANG=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

export EDITOR="emacsclient --no-wait"
export VISUAL="emacsclient"

export GOPATH=$HOME/go
# hide dwm name from jvm. Otherwise jwm complains about window manager
# and refuses to run from dwm.
if command -v wmname > /dev/null; then wmname LG3D; fi

# less/man colors
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"; a="${a%_}"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"; a="${a%_}"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"; a="${a%_}"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"; a="${a%_}"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"; a="${a%_}"
[ -f "$HOME/.dircolors" ] && eval "$(dircolors $HOME/.dircolors)"

# emacs26 need
export ALTERNATE_EDITOR=""

# to prevent any ugly gui popup
export SSH_ASKPASS=""

# common aliases
alias grep="grep --color=auto"
alias ll='ls -lah --color --group-directories-first'
alias ls='ls --color --group-directories-first'
alias ec='/usr/local/bin/emacsclient --no-wait'
alias et='/usr/local/bin/emacsclient -t'
alias sudoec='SUDO_EDITOR=/usr/local/bin/emacsclient sudoedit'
alias cls='printf "\033c"; stty sane'
alias pronounce='trans -speak -no-translate -j'
alias translate='trans -d -v :ru -j'
alias google-chrome='google-chrome-stable --enable-features=WebUIDarkMode --force-dark-mode'
alias file-explorer='xdg-open /'

if command -v fdfind > /dev/null; then alias fd='fdfind'; fi

# f1 for git status
bind '"\eOP":"git status\n"'
# Bind undo to just C-u instead of C-x C-u
stty kill undef
bind '"\C-u":undo'

[ -d "$HOME/.config/bash/bash_aliases.d" ] && for f in "$HOME/.config/bash/bash_aliases.d/"*; do
    source "${f}"
done

# fzf configuration
[ -f "$HOME/.config/bash/fzf.bash" ] && source "$HOME/.config/bash/fzf.bash"
# this is a secret
[ -f "$HOME/.config/bash/.bash_secret" ] && source "$HOME/.config/bash/.bash_secret"
# fzf-style bash completion
[ -f "$HOME/git/fzf-obc/bin/fzf-obc.bash" ] && source "$HOME/git/fzf-obc/bin/fzf-obc.bash"
# fzf-fasd configuration
[ -f "$HOME/.config/bash/fasd.bash" ] && source "$HOME/.config/bash/fasd.bash"
# git branch in prompt (Should be sources last to have proper error status)
[ -f "$HOME/.config/bash/bash_prompt" ] && source "$HOME/.config/bash/bash_prompt"

if [[ "$TERM" == "dumb" ]]; then
    PS1="> "
    PROMPT_COMMAND=""
fi

[ -f "$HOME/.bash_aliases" ] && . "$HOME/.bash_aliases"
[ -f "$HOME/.bashrc_work" ] && . "$HOME/.bashrc_work"
