#!/usr/bin/env bash

# shellcheck disable=SC1090

[ -d $HOME/.scripts ] && PATH="$PATH:$HOME/.scripts"
[ -d $HOME/.local/bin ] && PATH="$PATH:$HOME/.local/bin"

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
    exec startx
fi
